# Generated by Django 5.2.4 on 2025-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
