# Generated by Django 5.2.4 on 2025-08-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
