# Generated by Django 5.2.5 on 2025-08-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modele', to='home.modele')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gullar', to='home.name')),
                ('rangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rang', to='home.rang')),
            ],
        ),
    ]
